language: python
python:
 - "2.7"
install:
 - pip install -r requirements.txt
script:
 - nosetests smackdown/tests/
after_success:
 - coverage run --source=. smackdown/tests/tests_unit/test_webservices.py
 - coveralls
